  - name: download Pip
    get_url: url={{pip_download_url}} dest=/tmp/pip.tar.gz

  - name: download Setuptools
    get_url: url={{setuptools_download_url}} dest=/tmp/setuptools.tar.gz

  - name: delete pip
    file: path=/usr/bin/pip state=absent

  - name: untar pip
    shell: chdir=/tmp  tar zxvf pip.tar.gz -C /opt

  - name: chmod pip permission and owner groups
    file: path=/opt/pip-8.1.2 mode=777 owner=root group=root

  - name: untar Setuptools
    shell: chdir=/tmp  tar zxvf setuptools.tar.gz -C /opt

  - name: chmod setuptools permission and owner groups
    file: path=/opt/setuptools-23.0.0 mode=777 owner=root group=root

  - name: install Setuptools
    shell: chdir=/opt/setuptools-23.0.0 /usr/bin/python setup.py install

  - name: install pip
    shell: chdir=/opt/pip-8.1.2 /usr/bin/python setup.py install

  - name: link the pip
    shell: ln -sf /usr/local/bin/python2.7/bin/pip /usr/bin/pip

  - name: change the pip conf
    template: src=pip.conf.j2 dest=/etc/pip.conf

  - name: delete pip conf
    file: path=/root/.pip/pip.conf state=absent

  - name: change the pip conf
    template: src=pip.conf.j2 dest=/root/.pip/pip.conf
